engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby

  fixme:
    enabled: true

  rubocop:
    enabled: true
    # Check https://github.com/codeclimate/codeclimate-rubocop/branches/all?query=channel%2Frubocop
    channel: rubocop-1-31-0

ratings:
  paths:
  - "**.rb"

exclude_paths:
- spec/**/*
- certs/**/*
