engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby

  fixme:
    enabled: true

  rubocop:
    enabled: true
    channel: rubocop-0-58

ratings:
  paths:
  - "**.rb"

exclude_paths:
- spec/**/*
- certs/**/*
